<?php
/**
 * @auther Rtakaha
 */
namespace App\Controller;

use Cake\Event\Event;

class UsersController extends AppController {


    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->Auth->allow('add', 'logout');
    }

    public function index()
    {
        $users = $this->Users->find('all');
        $this->set(compact('users'));
    }

    public function view($id = null)
    {
//        $user = $this->Users->get($id);
        $user = $this->Users->get($id, ['contain' => ['Plans']]);
        $this->set(compact('user'));
    }

    /**
     * ユーザー登録
     * @author soufuru
     *
     */
    public function add()
    {
        $user = $this->Users->newEntity();
        if ($this->request->is('post')) {
            $user = $this->Users->patchEntity($user, $this->request->getData());
            if ($this->Users->save($user)) {
                $this->Flash->success(__('User registered.'));
                //登録後、どの画面に行くか
                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('User could not be registered. Please, try again.'));
            }
        }
        $this->set(compact('user'));
    }

    /**
     * ログイン
     * @author soufuru
     * @return \Cake\Http\Response|null
     */
    public function login(){
        if($this->request->is('post')) {
            $user = $this->Auth->identify();
            if ($user){
                $this->Auth->setUser($user);
                return $this->redirect($this->Auth->redirectUrl());
            } else {
                $this->Flash->error('Login failed');
            }
        }
    }

    /**
     * ログアウト
     * @author soufuru
     * @return \Cake\Http\Response|null
     */
    public function logout()
    {
        return $this->redirect($this->Auth->logout());
    }

}
